### ISSUE TITLE
Request: Machine-readable npm requirements

### ISSUE THREAD

**Issue by codyshepherd** [codyshepherd/lunar-rocks#43]
This will enable our CI to pick up any new dependencies on the node side automatically.

**Comment by codyshepherd** [comment]
Is there a package.json for global dependencies, or can we pass `npm install -g` a file?

**Comment by bgins** [comment]
I think we will be able to use `npm run` scripts along with `devDependencies` to do this. I have added what we need in #45. 

After calling `npm install`, we will want to call `npm run build-dev` in our dev environment and `npm run build-prod` in production.
